[
tool.poetry
]
name = "ad"
version = "0.1.0"
description = "Machine Learning Project with SQL Database"
authors = ["Keshav <khandelwalkeshav2004@gmail.copm>"]

[
tool.poetry.dependencies
]
python = "^3.10"
# Core Libraries
fastapi = "^0.95.1"
uvicorn = "^0.22.0"
sqlalchemy = "^2.0.10"
alembic = "^1.10.3"
psycopg2-binary = "^2.9.6"

# Machine Learning
scikit-learn = "^1.2.2"
pandas = "^2.0.1"
numpy = "^1.24.3"
mlflow = "^2.3.0"
joblib = "^1.2.0"

# Authentication
python-jose = "^3.3.0"
passlib = "^1.7.4"
python-multipart = "^0.0.6"

# Utilities
pydantic = "^1.10.7"
python-dotenv = "^1.0.0"

[
tool.poetry.group.dev.dependencies
]
# Development Dependencies
pytest = "^7.3.1"
coverage = "^7.2.5"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.3.0"
flake8 = "^6.0.0"

[
build-system
]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Linter and Formatter Configurations
[
tool.black
]
line-length = 100
target-version = ['py310']

[
tool.isort
]
profile = "black"
line_length = 100